### ISSUE TITLE
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by jordgey** [xiumingzhang/GenRe-ShapeHD#49]
Excuse me .I have this problem in the step ./build_toolbox.sh. My versions are CUDA8.0 pytorch0.4.1 gcc4.8.5/5.5( I have tried both).

**Comment by jordgey** [comment]
Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o calc_prob_kernel.cu.o calc_prob_kernel.cu -x cu -Xcompiler -fPIC -I /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include -I /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/TH -I /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC -I /home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src         -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61 
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/ATen/optional.h:19,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/ATen/Error.h:4,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/ATen/Allocator.h:6,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/TH/THAllocator.h:6,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:5,
                 from /home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4,
                 from calc_prob_kernel.cu:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/home/yao/GenRe-ShapeHD/toolbox/calc_prob
generating /tmp/tmp5ikfbzbw/_calc_prob_lib.c
setting the current directory to '/tmp/tmp5ikfbzbw'
running build_ext
building '_calc_prob_lib' extension
creating home
creating home/yao
creating home/yao/GenRe-ShapeHD
creating home/yao/GenRe-ShapeHD/toolbox
creating home/yao/GenRe-ShapeHD/toolbox/calc_prob
creating home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob
creating home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src
gcc -pthread -B /home/yao/anaconda2/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA=True -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src -I/home/yao/anaconda2/envs/shaperecon/include/python3.6m -c _calc_prob_lib.c -o ./_calc_prob_lib.o -std=c99
gcc -pthread -B /home/yao/anaconda2/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA=True -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src -I/home/yao/anaconda2/envs/shaperecon/include/python3.6m -c /home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.c -o ./home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.o -std=c99
gcc -pthread -shared -B /home/yao/anaconda2/envs/shaperecon/compiler_compat -L/home/yao/anaconda2/envs/shaperecon/lib -Wl,-rpath=/home/yao/anaconda2/envs/shaperecon/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_calc_prob_lib.o ./home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.o /home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob_kernel.cu.o -o ./_calc_prob_lib.so
gcc: error: /home/yao/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 54, in _build
    dist.run_command('build_ext')
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 45, in <module>
    ext.build()
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/cffi/recompiler.py", line 1527, in recompile
    compiler_verbose, debug)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yao/anaconda2/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 61, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by jordgey** [comment]
I have tried put export CXXFLAGS="-std=c++11" export CFLAGS="-std=c99" in the setup.sh and build_toolbox.sh ,but it did not work.

**Comment by jordgey** [comment]
And I install CUDA9.0 today, but error not changed.

**Comment by jordgey** [comment]
Would you mind share your gcc version? Thank you very much!

**Comment by zhukangle** [comment]
你好，我也遇到了类似的问题，你解决了吗？能否分享一下？
