### ISSUE TITLE
Fail to compile.

### ISSUE THREAD

**Issue by tiexuedanxin** [xiumingzhang/GenRe-ShapeHD#70]
hello, I followed the steps in README.md, but got errors when I use this command:
./build_toolbox.sh
The errors are as follows:

Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o calc_prob_kernel.cu.o calc_prob_kernel.cu -x cu -Xcompiler -fPIC -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/TH -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC -I /home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src         -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61 
nvcc fatal   : Unsupported gpu architecture 'compute_30'
/home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob
generating /tmp/tmp8r_iqc70/_calc_prob_lib.c
setting the current directory to '/tmp/tmp8r_iqc70'
running build_ext
building '_calc_prob_lib' extension
creating home
creating home/yong
creating home/yong/pycharm
creating home/yong/pycharm/GenRe-ShapeHD
creating home/yong/pycharm/GenRe-ShapeHD/toolbox
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=True -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c _calc_prob_lib.c -o ./_calc_prob_lib.o -std=c99
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=True -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c /home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.c -o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.o -std=c99
gcc -pthread -shared -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -L/home/yong/anaconda3/envs/shaperecon/lib -Wl,-rpath=/home/yong/anaconda3/envs/shaperecon/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_calc_prob_lib.o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob.o /home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob_kernel.cu.o -o ./_calc_prob_lib.so
gcc: error: /home/yong/pycharm/GenRe-ShapeHD/toolbox/calc_prob/calc_prob/src/calc_prob_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 42, in <module>
    ext.build()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/recompiler.py", line 1555, in recompile
    compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1
Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o nnd_cuda.cu.o nnd_cuda.cu -x cu -Xcompiler -fPIC -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/TH -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC -I /home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include        -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61
nvcc fatal   : Unsupported gpu architecture 'compute_30'
Including CUDA code.
/home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance
generating /tmp/tmprhj8yz5b/_my_lib.c
setting the current directory to '/tmp/tmprhj8yz5b'
running build_ext
building '_my_lib' extension
creating home
creating home/yong
creating home/yong/pycharm
creating home/yong/pycharm/GenRe-ShapeHD
creating home/yong/pycharm/GenRe-ShapeHD/toolbox
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c _my_lib.c -o ./_my_lib.o -std=c99
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c /home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib.c -o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib.o -std=c99
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c /home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib_cuda.c -o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib_cuda.o -std=c99
gcc -pthread -shared -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -L/home/yong/anaconda3/envs/shaperecon/lib -Wl,-rpath=/home/yong/anaconda3/envs/shaperecon/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_my_lib.o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib.o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/my_lib_cuda.o /home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/nnd_cuda.cu.o -o ./_my_lib.so
gcc: error: /home/yong/pycharm/GenRe-ShapeHD/toolbox/nndistance/src/nnd_cuda.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/recompiler.py", line 1555, in recompile
    compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1
Add -gencode to match all the GPU architectures you have.
Check 'https://en.wikipedia.org/wiki/CUDA#GPUs_supported' for list of architecture.
Check 'http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html' for GPU compilation based on architecture.
nvcc -c -o back_projection_kernel.cu.o back_projection_kernel.cu -x cu -Xcompiler -fPIC -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/TH -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include/THC -I /home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src -I /home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/lib/include        -gencode arch=compute_30,code=sm_30         -gencode arch=compute_35,code=sm_35         -gencode arch=compute_52,code=sm_52         -gencode arch=compute_61,code=sm_61
nvcc fatal   : Unsupported gpu architecture 'compute_30'
/home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp
/home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp
generating /tmp/tmp2n8h7i0j/_cam_bp_lib.c
setting the current directory to '/tmp/tmp2n8h7i0j'
running build_ext
building '_cam_bp_lib' extension
creating home
creating home/yong
creating home/yong/pycharm
creating home/yong/pycharm/GenRe-ShapeHD
creating home/yong/pycharm/GenRe-ShapeHD/toolbox
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp
creating home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=True -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c _cam_bp_lib.c -o ./_cam_bp_lib.o -std=c99
gcc -pthread -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA=True -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src -I/home/yong/anaconda3/envs/shaperecon/include/python3.6m -c /home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src/back_projection.c -o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src/back_projection.o -std=c99
gcc -pthread -shared -B /home/yong/anaconda3/envs/shaperecon/compiler_compat -L/home/yong/anaconda3/envs/shaperecon/lib -Wl,-rpath=/home/yong/anaconda3/envs/shaperecon/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_cam_bp_lib.o ./home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src/back_projection.o /home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src/back_projection_kernel.cu.o -o ./_cam_bp_lib.so
gcc: error: /home/yong/pycharm/GenRe-ShapeHD/toolbox/cam_bp/cam_bp/src/back_projection_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 43, in <module>
    ffi.build()
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/recompiler.py", line 1555, in recompile
    compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/yong/anaconda3/envs/shaperecon/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by ErinZhang1998** [comment]
I have a similar issue with this code, thanks for helping

**Comment by ztzhang** [comment]
cffi errors are probably due to pytorch verions. Newer versions do not support the cffi interface anymore.
