### ISSUE TITLE
When Training marrnet1, what should the argument 'classes' be

### ISSUE THREAD

**Issue by GimSungwoo** [xiumingzhang/GenRe-ShapeHD#8]
Hi there,

When Training marrnet1, how can I pass multiple classes. ?
 (i.e. --classes [ ] )
Cheers

**Comment by GimSungwoo** [comment]
I actually met the issue as below:

 Training
Epoch 1/1000
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    eval_at_start=opt.eval_at_start
  File "/mnt/mscteach_home/s1841522/mlpractical/GenRe-ShapeHD/models/netinterface.py", line 283, in train_epoch
    _train(epoch)
  File "/mnt/mscteach_home/s1841522/mlpractical/GenRe-ShapeHD/models/netinterface.py", line 255, in _train
    logger.on_epoch_end(epoch, epoch_log)
  File "/mnt/mscteach_home/s1841522/mlpractical/GenRe-ShapeHD/loggers/loggers.py", line 401, in on_epoch_end
    logger.on_epoch_end(epoch, epoch_log)
  File "/mnt/mscteach_home/s1841522/mlpractical/GenRe-ShapeHD/loggers/loggers.py", line 158, in on_epoch_end
    self.progbar.update(self.seen, self.log_values, force=True)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

**Comment by xiumingzhang** [comment]
Multiple classes are `+`-delimited, so you can do `--classes 03001627+04379243`.

Alternatively, you can name the set of your multiple classes by adding key-value pairs to the dictionary at https://github.com/xiumingzhang/GenRe-ShapeHD/blob/master/datasets/shapenet.py#L46. Then you can do `--classes your_set_name`.
